package task08;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class NodeParamsDialog extends JDialog {
    private JButton buttonCancel;
    private JButton buttonOk;
    private JPanel panelDialog;

    public NodeParamsDialog(boolean isRemove, ActionListener removeNode) {
        this.setContentPane(panelDialog);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setTitle(isRemove ? "Удалить вершину" : "Добавить вершину");
        buttonOk.setText(isRemove ? "Remove" : "Add");
        this.pack();


        this.setResizable(false);
        this.setLocationRelativeTo(null);

        buttonOk.addActionListener(e -> {
            removeNode.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, isRemove ? "removeNode" : "addNode"));
            setVisible(false);
        });
        buttonCancel.addActionListener(e -> {
            this.setVisible(false);
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelDialog = new JPanel();
        panelDialog.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        panelDialog.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonOk = new JButton();
        buttonOk.setText("Remove");
        panelDialog.add(buttonOk, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelDialog;
    }

}
